version: '3.8'

services:
  database:
    container_name: vac-compose-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=vacations
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    build: ./database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s

  backend:
    container_name: vac-compose-backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: vac-compose-frontend
    ports:
      - 5173:80
    build: ./frontend

  localstack:
    container_name: sn-localstack
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    build: ./localstack  # Ensure it builds from your Dockerfile
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - ./localstack/s3-data:/tmp/s3-data  # Mount your images into the container
